"""added cuisine

Revision ID: 84f55d20ca4a
Revises: aa149107dd07
Create Date: 2023-12-03 23:24:06.924386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f55d20ca4a'
down_revision = 'aa149107dd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('prep_time', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cook_time', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ingredients', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('preparation_steps', sa.Text(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_column('preparation_steps')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('cook_time')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('cuisine')

    # ### end Alembic commands ###
